### ISSUE TITLE
progressive zoom does not work with kinetic

### ISSUE THREAD

**Issue by codef0rmer** [davetayls/jquery.kinetic#15]
The progressive zooming does not work  in iPAD safari.

**Comment by kennardconsulting** [comment]
This library is still useful on iOS, even after all this time, as `-webkit-overflow-scrolling: touch`. If it helps anyone, you can enable pinch-to-zoom by doing:

```
filterTarget: function( target, e ) {
    if ( e.originalEvent.touches !== undefined && e.originalEvent.touches.length > 1 ) {
        return false;
    }
}
```
