### ISSUE TITLE
Click events.

### ISSUE THREAD

**Issue by paweu92** [davetayls/jquery.kinetic#68]
Hi,

On touch devices doesn't work click actions on divs. Do you have any solution?

Regards

**Comment by psrafo** [comment]
I have this problem too, thank's for link davetayls, it's solved our mistake.

**Comment by laciev** [comment]
Hi there!  I am new at JS (and so confused by it!).  I don't know where to paste the code to implement filtering. Kinetic is working in my page and its great, but my links don't work.  is there a certain area of the JS file to include this element?  Can someone guide me here?

**Comment by psrafo** [comment]
Try this.

	$("#content").kinetic({
		cursor: "auto",
		filterTarget: function(target, e) {
			if(!/down|start/.test(e.type))
			{
				return !(/a|img/i.test(target.tagName));
			}
		}
	});

**Comment by laciev** [comment]
Thanks but I'm not sure where to use it.. Is there any particular place in the js file that it should be?

**Comment by psrafo** [comment]
I can't explain it in this place, you need to forum (stackoverflow.com).
