### ISSUE TITLE
Help with target filtering

### ISSUE THREAD

**Issue by telegraphinho** [davetayls/jquery.kinetic#73]
Hello, i think that this plugin is quite amazing, but i have a small problem where i need to filter the target i want to scroll and i don't quite understand how to write it in the filterTarget method.

I want to be able to drag only ONE div with a particular id inside the wrapper, not all contents.

**Comment by davetayls** [comment]
not sure off the top of my head but try either setting the scroll position on the wrapper before you initialize `.kinetic()`
