### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Craga89** [davetayls/jquery.kinetic#86]
It would be helpful for those of us using a `webpack` or `browserify` build that this plugin be available directly on `npm`. Would you mind publishing? Should only take two minutes as the `package.json` looks suitable already!

**Comment by davetayls** [comment]
Done :smile: https://www.npmjs.com/package/jquery.kinetic

**Comment by Craga89** [comment]
:+1: very helpful! Thanks
