### ISSUE TITLE
filterTarget

### ISSUE THREAD

**Issue by kirkdm** [davetayls/jquery.kinetic#89]
Hey this would be a good plugin except for a few minor issues that could be fixed. The filtering method for tags doesn't allow focus on an input element so it "doesn't show the cursor when they have focus", and also you cant select text when you use the mouse, plus - on chrome when you touch move, the page scrolls slow and jerky during it's process that's the problems I'm having with your plugin. By the way I'm using a HP touch desktop computer.

$('body').kinetic({	
        filterTarget: function(target, e){
                if (!/down|start/.test(e.type)){
                     return !(/area|a|input|textarea/i.test(target.tagName));
                }
        }
});

Get back to me as soon as you can please thanks - Kirk

**Comment by davetayls** [comment]
Input filtering should be sorted thanks to #88 @tsaikd. 

Please attempt to fix and submit PRs for any issues found in future as I'm not actively developing this plugin any more.

Cheers
