### ISSUE TITLE
Click event does not work for "Child" when parent is using kinetic (Chrome Android)

### ISSUE THREAD

**Issue by hiphigi** [davetayls/jquery.kinetic#90]
When I attach the kinetic plugin to my photo reel, it works fine on my desktop PC, but on my Android mobile device it only allows you to slide/drag the photo reel, it does not allow you to click on the photos themselves.

The page is at http://lindseymotors.com/v if you click the default photo an expanded view pops up with a photo reel at the bottom. This is the element that has the kinetic plugin attached to it. When you click a photo, it should trigger the .click() function of viewVehiclePhoto($(this)) but does nothing on my mobile device.

This is how I'm attaching the plugin to the photo reel:

```
$('.vehicleDetailExpandedPhotoReel').kinetic({
    filterTarget: function(target, e){
        if (!/down|start/.test(e.type)){
            return !(/area|a|input/i.test(target.tagName));
        }
    }
});
```

**Comment by tsaikd** [comment]
I use iphone 6 to browse http://lindseymotors.com/v

1. initialization
2. scroll down a little
3. touch the photo
4. touch the photo again

the behavior just like first touch will focus on something, and the second touch will trigger the function you mentioned

I have no android device to test now, it's welcome to send PR for solving your problem.

![1](https://cloud.githubusercontent.com/assets/2329535/11169122/9abeeffa-8be9-11e5-8fba-eb3e1ab9357d.png)
![2](https://cloud.githubusercontent.com/assets/2329535/11169135/f575a236-8be9-11e5-9482-c24255ed6cd2.png)
![3](https://cloud.githubusercontent.com/assets/2329535/11169137/fdbd43d6-8be9-11e5-93bd-78efeb63c958.png)
![4](https://cloud.githubusercontent.com/assets/2329535/11169138/009eefaa-8bea-11e5-97f7-a0e8bdc82d07.png)

**Comment by dmitry-dedukhin** [comment]
See https://github.com/davetayls/jquery.kinetic/issues/93#issuecomment-262601590
