### ISSUE TITLE
Conflicts with sortable

### ISSUE THREAD

**Issue by iamdriz** [davetayls/jquery.kinetic#91]
I use Kinetic to allow dragging to scroll a panel that contains various items. These items can be re-ordered using the jQuery UI sortable module. However as the user clicks and drags to move an item it will also invoke the kinetic drag and cause the page to scroll meaning that the sortable item can't be moved up and down (because the page is moving behind it) and only be moved left and right.

Any ideas on how I could prevent this?

**Comment by tsaikd** [comment]
How about using `filterTarget` config to prevent drag?

**Comment by iamdriz** [comment]
@tsaikd What would I need to set as the filterTarget to allow sortable to work?

**Comment by tsaikd** [comment]
`filterTarget` used for enable/disable kinetic by custom check function

I think your filterTarget function should check if the target is not sortable item

the following example will make the '#b' is draggable, '#c' is not draggable
```
<div id='a'>
  <div id='b'></div>
  <div id='c'></div>
</div>
```
```
$('#a').kinetic({
  filterTarget: function(target, e) {
    // return true to enable kinetic on this element
    return $(target).is('#b');
  }
});
```

**Comment by iamdriz** [comment]
Due to the sortable elements having children target alone wasn't enough as the target could any number of the child nodes depending on where in the element you drag.

This worked:

~~~
$('.nano-content').kinetic({
	cursor: 'default',
	x: false,
	y: true,
	filterTarget: function(target, e) {
		if($(target).parents('#listApps').length > 0)
		   return false;
		else
			return true;	
	}
});
~~~
