### ISSUE TITLE
iOS Touch events do not work

### ISSUE THREAD

**Issue by BB-000** [davetayls/jquery.kinetic#93]
With this plugin enabled?

**Comment by BrockBeldham** [comment]
I've just noticed this also. Any solutions?

**Comment by Rhuantavan** [comment]
I have the same issue with tap events. Swipes do work, but the link below does not work unless I hold tap and choose to open the link.

I am simply calling `$('#projects-container').kinetic();`

**Comment by BrockBeldham** [comment]
Tt appears on ios (and probably other touch enabled devices) Kinetic uses 'touchstart'/'touchend'/'touchmove' instead of the traditional 'mousedown'/'mouseup'/'mousemove' events. It would seem that touch devices see this 'touchstart' instead of your click event. In other words, 'touchstart' events that start Kinetic on touch devices are given priority over any click events. I'm still messing around with Kinetic to see if I can find a solution, but I don't have much time till I'm pulled on to another project.

**Comment by zachrybaker** [comment]
For anyone who is still considering this plugin, I created a workaround you may be interested in by modifying _initEvents.  

Basically I watch that a move happens between touchStart and touchEnd, and if so I set self._movedSome to true.  When touchEnd (here called inputEnd) fires, it checks _movedSome, and if so then it will prevent the default event (click in this case).  If not, it prevents it.
`Kinetic.prototype._initEvents = function(){
    var self = this;
    self._movedSome = false;
    this.settings.events = {
      touchStart: function (e){
        var touch;
        if (self._useTarget(e.target, e)){
          touch = e.originalEvent.touches[0];
          self._movedSome = false;
          self.threshold = self._threshold(e.target, e);
          self._start(touch.clientX, touch.clientY);
          e.stopPropagation();
        }
      },
      touchMove: function (e){
        var touch;
        if (self.mouseDown){
          touch = e.originalEvent.touches[0];
          self._movedSome = true;
          self._inputmove(touch.clientX, touch.clientY);
          if (e.preventDefault){
            e.preventDefault();
          }
        }
      },
      inputDown: function (e){
        if (self._useTarget(e.target, e)){
          self.threshold = self._threshold(e.target, e);
          self._start(e.clientX, e.clientY);
          self.elementFocused = e.target;
          if (e.target.nodeName === 'IMG'){
            e.preventDefault();
          }
          e.stopPropagation();
        }
      },
      inputEnd: function (e){
        logger.log('inputEnd',e);
        if (self._useTarget(e.target, e)){
          self._end();
          self.elementFocused = null;

          if (self._movedSome === true) {
           self._movedSome = false;
           if(e.preventDefault) {
             e.preventDefault(); // don't let the event bubble.
           } 
          }
        }
      },
      inputMove: function (e){
        if (self.mouseDown){
          self._inputmove(e.clientX, e.clientY);
          self._movedSome = true;
          if (e.preventDefault){
            e.preventDefault();
          }
        }
      },
      scroll: function (e){
        if ($.isFunction(self.settings.moved)){
          self.settings.moved.call(self, self.settings);
          self._movedSome = true;
        }
        if (e.preventDefault){
          e.preventDefault();
        }
      },`

**Comment by dmitry-dedukhin** [comment]
I've solved this by the following

```
filterTarget: function(target, e) {
	// zero this.prevXPos mean that there was a click without move
	if (this.prevXPos == 0 && !/down|start/.test(e.type)) {
		return !(/a|img/i.test(target.tagName));
	}
},
```

**Comment by davetayls** [comment]
thanks @dmitry-dedukhin
