### ISSUE TITLE
Dropdown listing issue

### ISSUE THREAD

**Issue by iramtay** [davetayls/jquery.kinetic#98]
Dropdown listing in the page will not be able to be clicked.

Upon clicking the dropdown, it will closed immediately.

Is there any fix for this?

**Comment by davetayls** [comment]
You would need to use `filterTarget` to stop kinetic activating when clicking on the dropdown. see example in the docs

**Comment by iramtay** [comment]
Sorry, just tried with filterTarget and the dropdown will not appear.

$('.table-responsive').kinetic({
    filterTarget: function(target, e){
        if (!/down|up/.test(e.type)){
            return !(/select|area|a|input/i.test(target.tagName));
        }
    }
});
