### ISSUE TITLE
Memory Cleanup for GC

### ISSUE THREAD

**Issue by stevensanborn** [davetayls/jquery.kinetic#99]
Im getting a leak using kinetic on my div:

Its only keeping around elements after using kinetic on my scrollable content:

`$content.kinetic({
						x:false,
						y:true,
						cursor:"pointer",
						filterTarget: function(target, e){
					      return true;
					    }
					});
$content.kinetic('detach');
					
`
Detach is the only thing i see that does a kind of cleanup.
Is there a better to destroy this , its keeping my element around in the JS heap ?

**Comment by stevensanborn** [comment]
Added a pull request , not sure if that does the trick entirely but it got rid of the detached nodes held in memory after the kinetic element was removed from the dom.

https://github.com/davetayls/jquery.kinetic/pull/100

**Comment by tsaikd** [comment]
Merged
